version: "3.9"
services:
  steamcmd-valheim:
    build:
      context: .
    image: steamcmd-valheim:latest
    container_name: steamcmd-valheim
    environment:
      - VALHEIM_SERVER_PATH=${VALHEIM_SERVER_PATH:-/valheim}
      - VALHEIM_SERVER_SAV_DIR=${VALHEIM_SERVER_SAV_DIR:-/valheim_saves}
      - VALHEIM_SERVER_NAME=${VALHEIM_SERVER_NAME:-My Server}
      - VALHEIM_SERVER_WORLD=${VALHEIM_SERVER_WORLD:-Dedicated}
      - VALHEIM_SERVER_PASS=${VALHEIM_SERVER_PASS:-secret}
      - VALHEIM_SERVER_PUBLIC=${VALHEIM_SERVER_PUBLIC:-1}
    volumes:
      - valheim_server:/valheim
      - valheim_saves:/valheim_saves
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
    restart:
      always

volumes:
  valheim_server:
    name: valheim_server
    driver: local
  valheim_saves:
    name: valheim_saves
    driver: local