#!/bin/bash

steamcmd \
    +force_install_dir $VALHEIM_SERVER_PATH \
    +login $STEAMCMD_USER $STEAMCMD_PASS \
    +app_update $STEAMCMD_ID validate \
    +quit

export templdpath=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
export SteamAppId=892970

echo "Starting server PRESS CTRL-C to exit"

# Tip: Make a local copy of this script to avoid it being overwritten by steam.
# NOTE: Minimum password length is 5 characters & Password cant be in the server name.
# NOTE: You need to make sure the ports 2456-2458 is being forwarded to your server through your local router & firewall.
cd $VALHEIM_SERVER_PATH && exec $VALHEIM_SERVER_PATH/valheim_server.x86_64 \
    -name $VALHEIM_SERVER_NAME \
    -port 2456 \
    -world $VALHEIM_SERVER_WORLD \
    -password $VALHEIM_SERVER_PASS \
    -public $VALHEIM_SERVER_PUBLIC \
    -savedir $VALHEIM_SERVER_SAV_DIR

export LD_LIBRARY_PATH=$templdpath